#pip install nltk
#pip install wikipedia
#pip install requests
#pip install sympy
import os
import json
from datetime import datetime
import difflib
import requests
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")
from nltk.corpus import wordnet as wrdnet
import sympy
import re
import tkinter as tk
state = tk.DISABLED


#return cleaner
def clean_bot_response(response):
    if isinstance(response , (tuple,list)):
        response = response[0]
    response_str = str(response).strip()

    remove_this_prefix = ["Bot: ", "bot: "]
    for prefix in remove_this_prefix:
        if response_str.startswith(prefix):
            response_str=response_str[len(prefix):].strip()
    return response_str

WIKI_SEARCH_URL = "https://en.wikipedia.org/w/api.php"
WEATHER_URL = "https://api.open-meteo.com/v1/forecast"
GEOCODING_URL = "https://geocoding-api.open-meteo.com/v1/search"
WTTR_URL = "https://wttr.in"
memory_file = "memory.json"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
memory_file = os.path.join(BASE_DIR, "memory.json")

default_memory = {
    "name": None,
    "age": None,
    "address": None,
    "work": None
}
def save_memory():
    with open(memory_file,"w") as file:
        json.dump(memory,file,indent=4)

if os.path.exists(memory_file):
    try:
        with open(memory_file, "r") as file:
            memory = json.load(file)
    except (json.JSONDecodeError):
        memory = default_memory.copy()
else:
    memory=default_memory.copy()
    save_memory()
    
key_convo = [
    (["hello","hey","helo",
      "wassup","sup","whats up",
      "good morning", "good evening",
      "good afternoon", "namaste"], 
     "Hello! How can I help you?"),
    (["hi","hii","yo"], 
     "Hi! What's up? How can I help you today?"),
    (["how are you","how are you doing", 
      "how is the josh"],
     "I'm doing great! How about you?"),
    (["what is your name","what you do",
      "can you work","who are you",
      "tell us about yourself"],"I'm a Python ChatBot Created by NishantSh122. I can talk to you and answer your questions to my capabilities.")
]
terminators = {"exit","bye","goodbye","cya","good night","goodnight","close","shut up"}
weather_states = {
    "andhra pradesh",
    "arunachal pradesh",
    "assam",
    "bihar",
    "chhattisgarh",
    "goa",
    "gujarat",
    "haryana",
    "himachal pradesh",
    "jharkhand",
    "karnataka",
    "kerala",
    "madhya pradesh",
    "maharashtra",
    "manipur",
    "meghalaya",
    "mizoram",
    "nagaland",
    "odisha",
    "punjab",
    "rajasthan",
    "sikkim",
    "tamil nadu",
    "telangana",
    "tripura",
    "uttar pradesh",
    "uttarakhand",
    "west bengal"
}
weather_tags = {
    "weather", "temperature","climate","forecast"
}
location_markers = [" in ", " at ", " for ", " of ", " near "]
trailing_noise = {"today","now","right","now?","currently","please","tomorrow","tonight"}
time_tags={
    "time", "clock", "current time"
}
question_wrds = {
    "what", "who", "where", "when", "why", "how", "define", "explain", "elaborate", "describe", "discuss", "generate", "tell"
}
starting_phrases = [
    "can you explain",
    "tell me about","do you know about",
    "what is","what are",
    "what was","who is",
    "who was","where is",
    "where was","when is","when was",
    "why is","why was",
    "how is","how does",
    "how do","define",
    "explain","describe"
]
pfp_phrase = {
    "my name",
    "who am i",
    "your opinion",
    "do you love",
    "do you like me"
}
define_phrase={
    "define", "what is the meaning of",
    "definition of", "what does",
    "meaning by", "meaning of","what do you mean by", "what is the meaning of"
}

#creating the biggest dataset of this project
#this section was generated by chatgpt
intents = {
    "weather": {
        "keywords": [
            "weather",
            "temperature",
            "climate",
            "forecast",
            "rain",
            "raining",
            "hot",
            "cold",
            "humid",
            "humidity",
            "wind",
            "windy"
        ]
    },

    "math": {
        "keywords": [
            "calculate",
            "solve",
            "simplify",
            "differentiate",
            "derivative",
            "integrate",
            "integral",
            "factorize",
            "factor",
            "expand",
            "limit",
            "square root",
            "sqrt"
        ]
    },

    "time": {
        "keywords": [
            "time",
            "clock",
            "current time"
        ]
    },

    "definition": {
        "keywords": [
            "define",
            "definition",
            "meaning",
            "what does",
            "what do you mean"
        ]
    },

    "wikipedia": {
        "keywords": [
            "what is",
            "what are",
            "who is",
            "who was",
            "where is",
            "where was",
            "when was",
            "when is",
            "why is",
            "how does",
            "tell me about",
            "explain",
            "describe"
        ]
    }
}

#fetching name for the user data
def get_name(text):
    phrases= [
        "my name is",
        "i am", "i'm"
    ]
    for phrase in phrases:
        if text.startswith(phrase + " "):
            name = text[len(phrase):].strip()
            if name:
                return name
    return None

#fetching user age for data
def get_age(text):
    words = text.split()
    if text.startswith("my age is "):
        age = text[len("my age is "):].strip()
        age = age.replace(" years old", "")
        age = age.replace(" years", "")
        age = age.replace(" year old", "")
        age = age.replace(" year", "")
        if age.isdigit():
            return int(age)
    if text.startswith("i am "):
        age = text[len("i am "):].strip()
        age = age.replace(" years old", "")
        age = age.replace(" years", "")
        age = age.replace(" year old", "")
        age = age.replace(" year", "")
        if age.isdigit():
            return int(age)
    return None

#fetching address
def get_address(text):
    if text.startswith("my address is"):
        return text[len("my address is"):].strip()
    if text.startswith("i live in"):
            return text[len("i live in"):].strip()
    return None

#data collecting center
def memory_response(text):
    if "what is my name" in text or "what's my name" in text:
        if memory["name"] is not None:
            return "your name is " + memory["name"] + "."
        return "I don't know your name yet."
    if "who am i" in text:
        if memory["name"] is not None:
            return "You are " + memory["name"] + "."
        return "I don't know your name yet."
    if "how old am i" in text:
        if memory["age"] is not None:
            return "You are " + str(memory["age"]) + " years old."
        return "I don't know your age yet."
    if "what is my age" in text:
        if memory["age"] is not None:
            return "You are " + str(memory["age"]) + " years old."
        return "I don't know your age yet."
    if "what is my address" in text:
        if memory["address"] is not None:
            return "Your address is " + memory["address"] + "."
        return "I don't know your address yet."
    if "where do i live" in text:
        if memory["address"] is not None:
            return "Your address is " + memory["address"] + "."
        return "I don't know your address yet."
    return None

#removing punctuations and unwanted spaces
def normalisation(text):
    text = text.strip().lower() #remove space #lowerspace
    if text.startswith("you:"):
        text = text[4:].strip()
    for ch in ["?","!",",","'"]:
        text=text.replace(ch,"") #replacing the character with an empty character literal
    text = ' '.join(text.split()) #splitting large space and resulting in one string with just one space between characters
    return text

#adding fuzzy matching technique.
#Fuzzy matching, or approximate string matching, 
# is a computer technique that finds text strings, words, 
# or data records that are similar rather than exact matches. 
# It assigns a similarity score to handle typos, spelling errors, 
# abbreviations, and formatting differences.
def fuzzy_match(text,choices,cutoff=0.7):
    match = difflib.get_close_matches(
        text, choices, n=1, cutoff = cutoff
    )
    if match:
        return match[0]
    return None

def contains_keyword(text,keywords):
    words = text.split()
    for keyword in keywords:
        keyword_words = keyword.split()
        if len(keyword_words) ==1:
            if keyword in words:
                return True
        else:
            if keyword in text:
                return True
    return False

#making an intention detector so that this cool bot can give answers based on users intention
def intent_detector(text):
    scores = {}
    for intent_name,data in intents.items():
        score = 0
        words = text.split()
        for keyword in data["keywords"]:
            if contains_keyword(text,[keyword]):
                score +=1
                continue
            if " " not in keyword:
                match = fuzzy_match(keyword, words, cutoff=0.8)
                if match is not None:
                    score += 1
        scores[intent_name] =score
    top_intent = max(scores,key=scores.get)
    # if ismques(text):
    #     return "math"
    # if scores[top_intent]==0:
    #     return None
    
    #filter check
    #jarurat nhi thi aise hi dal diya :)
    if ismques(text):
        return "math"
    if isdques(text):
        return "definition"
    if isweather(text):
            return "weather"
    if istques(text):
        return "time"
    if isfques(text):
            return "wikipedia"
    return top_intent

#segregating the words to be handled by apis. THE SO CALLED ENTITIES
def extract_entities(text,intent):
    entities = {}
    if intent == "weather":
        location = get_location(text)
        if location is not None:
            entities["location"] = location
    return entities
#checking question tags
def isfques(text):
    if not text:
        return False
    for phrase in pfp_phrase:
        if phrase in text:
            return False
    word_1 = text.split()[0]
    if word_1 in question_wrds:
        return True
    else:
        return False

#checking define quesiton tags
def isdques(text):
    for phrase in define_phrase:
        if text.startswith(phrase + " "):
            return True
    return False

#removing the question tags and leaving behind the keys to be searched up on wiki
def get_topics(text):
    sorted_phrases = sorted(starting_phrases, key=len, reverse=True)
    for phrase in sorted_phrases:
        prefix = phrase + " "
        if text.startswith(prefix):
            text = text[len(prefix):].strip()
            break
    return text.strip()
headers = {
    'User-Agent': 'PythonBot/1.0 (contact@example.com)'
}

#searching the word
def look_wiki(topic):
    try:
        response_wiki = requests.get(
            WIKI_SEARCH_URL,
            headers=headers,
            params = {
                "action":"query",
                "list":"search",
                "srsearch": topic,
                "srlimit":5,
                "format":"json"
            },
            timeout=10
        )
        response_wiki.raise_for_status()
        data = response_wiki.json()
        results = data.get("query",{}).get("search",[])
        titles=[result["title"] for result in results]
        return titles
    except requests.exceptions.RequestException as e:
        print("API Error:", e)
        return None

#chosing the top topic for the user
def top_wiki_title(topic, titles):
    if not titles:
        return None
    lower_titles = [t.lower() for t in titles]
    matches = difflib.get_close_matches(
        topic.lower(),
        lower_titles,
        n=1, #selecting the first topic for the wiki search/summary
        cutoff=0.5 #no results that are way too off --> feature of bot
    )
    if matches:
        matched_index = lower_titles.index(matches[0])
        return titles[matched_index]
    return None

#using the above method and getting summary
def get_sumry(title):
    concatenated_title = requests.utils.quote(title,safe="")
    url = ("https://en.wikipedia.org/api/rest_v1/page/summary/" + concatenated_title)
    try:
        response = requests.get(
            url,headers = headers, timeout=10
        )
        response.raise_for_status()
        data=response.json()
        return data.get("extract") #wikipedia response name (default)
    except requests.exceptions.RequestException:
        return None

#final call directly to the wikipedia
def get_wikipedia(topic):
    titles = look_wiki(topic)
    if titles is None:
        return None
    if not titles:
        return None
    title = top_wiki_title(
        topic,titles
    )
    if title is None:
        return None
    sumry = get_sumry(title)
    if sumry is None:
        return None
    if isAmbiguity(sumry):
        return None
    return title, sumry

#removing ambiguity of words
def isAmbiguity(sumry):
    if not sumry:
        return True
    if "may refer to:" in sumry.lower() and len(sumry)<200:
        return True
    return False

#removing the definition question tags and leaving behind the keys to be searceh up on wordnet
def get_word(text):
    sorted_phrases = sorted(define_phrase, key=len, reverse=True)
    for phrase in sorted_phrases:
        prefix = phrase + " "
        if text.startswith(prefix):
            return text[len(prefix):].strip()
    return None

#adding nltk library to get a more good response for definintions of words.
def get_definition(text):
    if not text:
        return None
    synsets = wrdnet.synsets(text)
    if not synsets:
        return None
    definition = synsets[0].definition()
    example_sentences = synsets[0].examples()
    # print(definition, example_sentences)
    return definition, example_sentences

#weather detecting 
def isweather(text):
    for tags in weather_tags:
        if tags in text:
            return True
    return False

#getting location data
def get_location(text):
    padded = " " + text + " "
    best_idx = -1
    best_marker_len = 0
    for marker in location_markers:
        idx = padded.find(marker)
        if idx != -1 and (best_idx == -1 or idx < best_idx):
            best_idx = idx
            best_marker_len = len(marker)
    if best_idx == -1:
        return None
    
    location= padded[best_idx + best_marker_len:].strip()

    
    for tag in weather_tags:
        location = location.replace(tag, "").strip()
    words = [w for w in location.split() if w not in trailing_noise]
    location = " ".join(words)
    return location if location else None

#getting weather details
def get_mausam(place):
    try:
        response = requests.get(
            WTTR_URL + "/" + requests.utils.quote(place),
            params={"format": "j1"},
            headers=headers, timeout=10
        )
        response.raise_for_status()
        data = response.json()
        current = data.get("current_condition", [None])[0]
        area = data.get("nearest_area", [None])[0]
        if current is None:
            return None, None
        resolved_name = None
        if area:
            area_name = area.get("areaName", [{}])[0].get("value")
            region = area.get("region", [{}])[0].get("value")
            resolved_name = area_name if area_name else region
        return current, resolved_name
    except requests.exceptions.RequestException as e:
        print("Weather API Error:", e)
        return None, None

#decoding the weather codes
def weather_decoder(code):
    weather_codes ={
        0: "Clear sky",
        1: "Mainly clear",
        2: "Partly cloudy",
        3: "Overcast",
        45: "Foggy",
        48: "Depositing rime fog",
        51: "Light drizzle",
        53: "Moderate drizzle",
        55: "Dense drizzle",
        61: "Slight rain",
        63: "Moderate rain",
        65: "Heavy rain",
        71: "Slight snowfall",
        73: "Moderate snowfall",
        75: "Heavy snowfall",
        80: "Slight rain showers",
        81: "Moderate rain showers",
        82: "Violent rain showers",
        95: "Thunderstorm",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail"
    }
    return weather_codes.get(code,"Weather condition unavailable")

#giving back all weather data 
    
#api response collector
def weather_response(place):
    result, resolved_name = get_mausam(place)
    if result is None:
        return None
    temperature = result.get("temp_C")
    humidity = result.get("humidity")
    wind = result.get("windspeedKmph")
    condition = result.get("weatherDesc", [{}])[0].get("value", "Weather condition unavailable")
    display_name = (resolved_name or place).title()
    return(
        "Weather in " + display_name + ":\n"
        "Temperature: " + str(temperature) + "°C\n"
        "Condition: " + condition + "\n"
        "Humidity: " + str(humidity) + "%\n"
        "Wind speed: " + str(wind) + " km/h"
    )
    
#is time ques chekcer
def istques(text):
    for phrase in time_tags:
        if phrase in text:
            return True
    return False
def get_time():
    current_time= datetime.now()
    return current_time.strftime("%I:%M:%S %p")

#maths tags and operators
def ismques(text):
    math_tags = {
        "calculate",
        "solve",
        "simplify",
        "differentiate",
        "derivative",
        "integrate",
        "integral",
        "factorize",
        "factor",
        "expand",
        "limit",
        "sqrt",
        "square root"
    }
    if any(operator in text for operator in ["-","+","/","*","^","=","√"]):
        return True
    for tag in math_tags:
        if tag in text:
            return True
    return False
def correct_phrase_if_incorrect(text):
    math_phrases = [
        "calculate",
        "solve",
        "simplify",
        "differentiate",
        "derivative",
        "integrate",    
        "integral",
        "factorize",
        "factor",
        "expand",
        "limit",
        "sqrt",
        "square root"
    ]
    words = text.split()
    if not words:
        return text
    first_word = words[0]
    if first_word in math_phrases:
        return text
    match = fuzzy_match(first_word, math_phrases, cutoff=0.7)
    if match is not None:
        words[0] = match
        return " ".join(words)
    return text

def convert_math_Exp(text):
    mat_phrases={
        "please calculate", "please answer", "calculate", "solve the",
        "solve", "simplify", "differentiate", "derivative of", "derivative",
        "integrate", "integral of", "integral", "factorize", "factor",
        "expand", "limit", "sqrt", "square root", "find the value of x in",
        "find the value of", "find the", "what is", "value of"
    }
    expression = text.lower()
    for tag in sorted(mat_phrases,key=len,reverse=True):
        if tag in expression:
            expression = expression.replace(tag,"").strip()
            break
    expression = re.sub(r'(\d)([a-zA-Z\(])', r'\1*\2', expression) #regix
    return expression

def solver(text):
    try:
        text=correct_phrase_if_incorrect(text)
        #trying to make differentiation bot
        if text.startswith("differentiate ") or text.startswith("derivative of "):
            prefix = "differentiate " if text.startswith("differentiate ") else "derivative of "
            expression = convert_math_Exp(text[len(prefix):].strip())
            x = sympy.Symbol("x")
            expression = expression.replace("^","**")
            result = sympy.diff(sympy.sympify(expression),x)
            return "Derivative: "+str(result)
        # if text.startswith("derivative of "):
        #     expression = convert_math_Exp[len("derivative of "):].strip()
        #     x = sympy.Symbol("x")
        #     expression = expression.replace("^", "**")
        #     result = sympy.diff(sympy.sympify(expression),x)
        #     return "Derivative: " + str(result)
        
        #test for integration
        if text.startswith("integrate ") or text.startswith("integral of "):
            prefix = "integrate " if text.startswith("integrate ") else "integral of "
            expression = text[len(prefix):].strip()
            x = sympy.Symbol("x")
            expression = expression.replace("^","**")
            result = sympy.integrate(sympy.sympify(expression),x)
            return "Integral: " + str(result) + " + C"
        # if text.startswith("integral of"):
        #     expression = text[len("integral of "):].strip()
        #     x = sympy.Symbol("x")
        #     expression = expression.replace("^","**")
        #     result = sympy.integrate(sympy.sympify(expression),x)
        #     return "Integral: " + str(result) + " + C"
        
        #testing limit exp
        if text.startswith("limit "):
            expression = text[len("limit "):].strip()
            #limit x^3 as x approches 3
            #limit x^3 (x->3)
            if " as x approaches " in expression:
                parts = expression.split(" as x approaches ")
                equation = convert_math_Exp(parts[0].strip()).replace("^","**")
                value = parts[1].strip()
                x = sympy.Symbol("x")
                result = sympy.limit(sympy.sympify(equation), x, sympy.sympify(value))
                return "Limit: " +str(result)
            return "Please use: limit expression as x approaches value"
        #factors
        if text.startswith("factorize") or text.startswith("factor"):
            prefix = "factorize " if text.startswith("factorize ") else "factor "
            expression = convert_math_Exp(text[len("factorize "):].strip()).replace("^","**")
            result = sympy.factor(sympy.sympify(expression))
            return "Factorized: " + str(result)
        
        #equations
        if "=" in text:
            clean_text = convert_math_Exp(text)
            parts =clean_text.split("=")
            if len(parts) == 2:
                left = parts[0].strip().replace("^", "**")
                right = parts[1].strip().replace("^", "**")
                x= sympy.Symbol("x")
                equation = sympy.Eq(sympy.sympify(left) , sympy.sympify(right))
                result = sympy.solve(equation,x)
                if result:
                    return "x = "+str(result)
                return "No solution found."
        
        #simplify questions
        if text.startswith("simplify "):
            expression = convert_math_Exp(text[len("simplify "):].strip()).replace("^","**")
            result = sympy.simplify(sympy.sympify(expression))
            return "Simplified: " + str(result)
        
        #expand the following questions
        if text.startswith("expand "):
            expression = convert_math_Exp(text[len("expand "):].strip()).replace("^","**")
            # expression = expression.replace("^","**")
            result=sympy.expand(sympy.sympify(expression))
            return "Expanded: " + str(result)
        
        #easy peasy calc
        expression = convert_math_Exp(text)
        expression = expression.replace("^","**").replace("√","sqrt")
        result = sympy.sympify(expression)
        return "Answer: " + str(result)
    
    except Exception as e:
        print("Math Error name - ", e)
        return None
def fllwup(text):
    fllwup_phrases={
        "what about", "how about","and tomorrow",
        "and today", "what about tomorrow",
        "what about today", "how about tomorrow","how about today",
        "there", "that place", "the same place"
    }
    for phrase in fllwup_phrases:
        if phrase in text:
            return True
    return False

#IMPORTANT CONTEXT STORAGE TO GET A CONTINUOUS FLOW
context={
    "last_intent" : None,
    "last_location" : None,
    "last_topic" : None,
}

awaiting_location = False

#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN # 
#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN #
#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN #

def main_data(raw):
    global awaiting_location
    user = raw
    user = normalisation(user)
    
    #terminating words
    if user in terminators:
        raw_response ="Bot: Goodbye!"
        return clean_bot_response(raw_response)
        # break
        
    for keywords, reply in key_convo:
        if contains_keyword(user,keywords):
            return clean_bot_response("Bot: " + reply)
    
    #storage
    name = get_name(user)
    if name is not None:
        memory["name"]=name
        save_memory()
        raw_response = "Bot: Nice to meet you, "+name+"!"
        return clean_bot_response(raw_response)
        # continue
    age = get_age(user)
    if age is not None:
        memory["age"]=age
        save_memory()
        raw_response = "Bot: I'll remember that you are " + str(age) + " years old."
        return clean_bot_response(raw_response)
        # continue
    address = get_address(user)
    if address is not None:
        memory["address"] = address
        save_memory()
        raw_response = "Bot: I'll remember that you live in " + address + "."
        return clean_bot_response(raw_response)
        # continue
    
    memory_result = memory_response(user)
    if memory_result is not None:
        raw_response = "Bot:", memory_result 
        return clean_bot_response(raw_response)
        # continue
    
    #state word check
    if awaiting_location:
        awaiting_location = False
        place = user.strip() or get_location(user)
        if not place:
            raw_response = "Bot: Please enter a location"
            return clean_bot_response(raw_response)
            
        context["last_location"]= place
        context["last_intent"]="weather"
        result = weather_response(place)
        if result is None:
            raw_response = "Bot: Sorry, I couldn't find weather data for '" + place + "'. Try a nearby bigger city or check the spelling?"
            return clean_bot_response(raw_response)
        else:
            raw_response ="Bot: "+result
            return raw_response
        # continue
    
    
    intent = intent_detector(user)
    entities = extract_entities(user,intent)
    if fllwup(user):
        if context["last_intent"] is not None:
            intent= context["last_intent"]
        if context["last_location"] is not None:
            entities["location"] = context["last_location"]
    # print("Intent:", intent)
    # print("Entities:", entities)
    
    #weather report
    if intent=="weather":
        place = entities.get("location")
        if place is not None:
            context["last_location"] = place
            
        if place is None:
            awaiting_location=True
            raw_response = "Bot: Which state would you like the weather for?"
            return clean_bot_response(raw_response)
            # continue
        result=weather_response(place)
        if result is None:
            raw_response = "Bot: Sorry, I couldn't find weather data for '" + place + "'. Try a nearby bigger city or check the spelling?"
            return clean_bot_response(raw_response)
        else: 
            raw_response = "Bot: "+ result
            return clean_bot_response(raw_response)
        
        context["last_intent"]="weather"
        # continue
    
    #time report
    if intent=="time":
        current_time = get_time()
        raw_response = "Bot: The current time is"+ current_time
        return clean_bot_response(raw_response)
        # continue
    
    #math caclulations
    if intent=="math":
        result = solver(user)
        if result is not None:
            raw_response ="Bot: "+result
            return clean_bot_response(raw_response)
        else:
            raw_response = "Bot: I couldn't solve that mathematical expression."
            return clean_bot_response(raw_response)
        # continue
    
    #key_word looker
    found = False
    for keywords, reply in key_convo:
        #runs till each element in keywords
        if contains_keyword(user,keywords):
            raw_response = "Bot:"+reply
            return clean_bot_response(raw_response)
            found = True
            break
    # if found:
    #     # continue
    
    #definition check
    if intent=="definition":
        word = get_word(user)
        result = get_definition(word)
        if result is None:
            result1 = get_wikipedia(word)
            if result1 is None:
                raw_response = "I am still an undertrained chatbot. I don't know the above information. Please feel free to ask something else."
                return clean_bot_response(raw_response)
            else:
                title, sumry = result1
                raw_response = "Bot: "+sumry+"\n/source" + title
                return clean_bot_response(raw_response)
                # ("/source:",title)
            # continue
        else:
            define, example = result #adds result values of get_definiton(returns define and example)
            print("Bot:", define) #prints word and its sentence
            if example:
                raw_response = "The word can be used as : "+ example[0]
                return clean_bot_response(raw_response)
        # continue
    
    #ques check
    if intent=="wikipedia":
        topic = get_topics(user)
        result = get_wikipedia(topic)
        if result is None:
            raw_response = "I am still an undertrained chatbot. I don't know the above information. Please feel free to ask something else."
            return clean_bot_response(raw_response)
        else:
            title, sumry = result
            raw_response = "Bot: "+sumry+"\n/source" + title
            return clean_bot_response(raw_response)
        # continue

    #if passes fails all the tests above then execute this at end;
    raw_response = "Bot: Sorry, I don't understand that yet."
    return clean_bot_response(raw_response)

root = tk.Tk()
root.title("Jaggery")
root.geometry("450x600")
root.configure(bg="#0A0A0A")

header_frame = tk.Frame(root, bg="#080808")
header_frame.pack(fill=tk.X)

#header content
header_label = tk.Label(
    header_frame,
    text="Jaggery",
    font = ("Helvetica", 12, "bold"),
    fg="#FFC107", 
    bg="#080808"
)

#alignment
header_label.pack(side=tk.LEFT, padx=15, pady=10)

def clear_chat():
    for child in scrollable_frame.winfo_children():
        child.destroy()

#dlt button
clear_btn = tk.Button(
    header_frame,
    text="Clear Chat",
    font=("Helvetica",9,"bold"),
    bg="#EF4444", 
    fg="#F5F5F5",
    bd = 0,
    padx = 10,
    pady = 3,
    command = clear_chat #linking the button
)
clear_btn.pack(side=tk.RIGHT, padx=15)

chat_container = tk.Frame(root, bg="#0F0F0F")
chat_container.pack(padx=10, pady=10, fill= tk.BOTH, expand = True)

canvas = tk.Canvas(chat_container, bg="#0F0F0F", highlightthickness=0)
scrollbar = tk.Scrollbar(
    chat_container,
    command=canvas.yview,
    bg="#171717",
    troughcolor="#0A0A0A",
    activebackground="#FFC107"
)
scrollable_frame = tk.Frame(canvas,bg="#181825")
scrollable_frame.bind(
    "<Configure>",
    lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
)
canvas.create_window((0,0), window=scrollable_frame, anchor="nw")
canvas.configure(yscrollcommand=scrollbar.set)
canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
canvas.bind(
    "<Configure>",
    lambda e: canvas.itemconfig(canvas.find_withtag("all")[0], width=e.width)
)

#msg renderer
def add_message_bubble(message, sender="user"):
    row_frame = tk.Frame(scrollable_frame, bg = "#181825", pady=4)
    row_frame.pack(fill=tk.X, expand=True)

    #design sender
    if sender=="user":
        bg_color = "#0A0A0A"
        fg_color ="#FFD43B"
        anchor_side=tk.RIGHT
        label_title = "You"
    else:
        bg_color = "#171717"
        fg_color = "#cdd6f4"
        anchor_side = tk.LEFT
        label_title = "Bot"
        
    #frame
    bubble_frame=tk.Frame(row_frame, bg = bg_color, padx=10, pady= 6)
    title_lbl = tk.Label(
        bubble_frame, text=label_title,
        font=("Helvetica", 8, "bold"),
        bg=bg_color,
        fg="#A3A3A3" if sender == "user" else "#FFFFFF"
    )
    title_lbl.pack(anchor="w" if sender == "bot" else "e",fill=tk.X)
    
    msg_lbl = tk.Label(
        bubble_frame, 
        text=str(message), 
        font=("Helvetica", 10),
        bg=bg_color, 
        fg=fg_color, 
        wraplength=220,
        justify=tk.LEFT if sender == "bot" else tk.RIGHT
    )
    msg_lbl.pack(anchor="w" if sender == "bot" else "e", fill=tk.X)
    bubble_frame.pack(side = anchor_side, padx=10)

    scrollable_frame.update_idletasks()
    canvas.update_idletasks()
    canvas.yview_moveto(1.0)

input_frame = tk.Frame(root,bg="#080808", pady=10, padx=10)
input_frame.pack(fill=tk.X, side=tk.BOTTOM)

#user entry
user_entry = tk.Entry(
    input_frame,
    font=("Helvetica",11),
    bg="#171717",
    fg="#F5F5F5",
    insertbackground="#FFC107",
    bd = 0,
    relief=tk.FLAT
)
user_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, ipady = 6, padx=(0,8))
user_entry.focus()

#finally send button
send_btn = tk.Button(
    input_frame,
    text="Send",
    font=("Helvetica", 10,"bold"),
    bg="#FFC107", 
    fg="#0A0A0A", 
    bd=0, 
    padx=15, 
    pady=4
    
)
send_btn.pack(side=tk.RIGHT)

#message handler
def send_message():
    raw_txt = user_entry.get().strip()
    if not raw_txt:
        return
    add_message_bubble(raw_txt, sender="user")
    user_entry.delete(0,tk.END)
    bot_response = main_data(raw_txt)
    add_message_bubble(bot_response,sender="bot")
send_btn.config(command=send_message)
user_entry.bind("<Return>", lambda event: send_message())
#header

root.mainloop()