#pip install nltk
#pip install wikipedia
#pip install requests
import os
import json
from datetime import datetime
import difflib
import requests
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")
from nltk.corpus import wordnet as wrdnet
import sympy

WIKI_SEARCH_URL = "https://en.wikipedia.org/w/api.php"
WEATHER_URL = "https://api.open-meteo.com/v1/forecast"
GEOCODING_URL = "https://geocoding-api.open-meteo.com/v1/search"
WTTR_URL = "https://wttr.in"
memory_file = "memory.json"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
memory_file = os.path.join(BASE_DIR, "memory.json")

default_memory = {
    "name": None,
    "age": None,
    "address": None,
    "work": None
}
def save_memory():
    with open(memory_file,"w") as file:
        json.dump(memory,file,indent=4)

if os.path.exists(memory_file):
    try:
        with open(memory_file, "r") as file:
            memory = json.load(file)
    except (json.JSONDecodeError):
        memory = default_memory.copy()
else:
    memory=default_memory.copy()
    save_memory()
    
key_convo = [
    (["hello","hey","helo",
      "wassup","sup","whats up",
      "good morning", "good evening",
      "good afternoon", "namaste"], 
     "Hello! How can I help you?"),
    (["hi","hii","yo"], 
     "Hi! What's up? How can I help you today?"),
    (["how are you","how are you doing", 
      "how is the josh"],
     "I'm doing great! How about you?"),
    (["what is your name","what you do",
      "can you work","who are you",
      "tell us about yourself"],"I'm a Python ChatBot Created by NishantSh122. I can talk to you and answer your questions to my capabilities.")
]
terminators = {"exit","bye","goodbye","cya","good night","goodnight","close","shut up"}
weather_states = {
    "andhra pradesh",
    "arunachal pradesh",
    "assam",
    "bihar",
    "chhattisgarh",
    "goa",
    "gujarat",
    "haryana",
    "himachal pradesh",
    "jharkhand",
    "karnataka",
    "kerala",
    "madhya pradesh",
    "maharashtra",
    "manipur",
    "meghalaya",
    "mizoram",
    "nagaland",
    "odisha",
    "punjab",
    "rajasthan",
    "sikkim",
    "tamil nadu",
    "telangana",
    "tripura",
    "uttar pradesh",
    "uttarakhand",
    "west bengal"
}
weather_tags = {
    "weather", "temperature","climate","forecast"
}
location_markers = [" in ", " at ", " for ", " of ", " near "]
trailing_noise = {"today","now","right","now?","currently","please","tomorrow","tonight"}
time_tags={
    "time", "clock", "current time"
}
question_wrds = {
    "what", "who", "where", "when", "why", "how", "define", "explain", "elaborate", "describe", "discuss", "generate", "tell"
}
starting_phrases = [
    "can you explain",
    "tell me about","do you know about",
    "what is","what are",
    "what was","who is",
    "who was","where is",
    "where was","when is","when was",
    "why is","why was",
    "how is","how does",
    "how do","define",
    "explain","describe"
]
pfp_phrase = {
    "my name",
    "who am i",
    "your opinion",
    "do you love",
    "do you like me"
}
define_phrase={
    "define", "what is the meaning of",
    "definition of", "what does",
    "meaning by", "meaning of","what do you mean by", "what is the meaning of"
}

#creating the biggest dataset of this project
#this section was generated by chatgpt
intents = {
    "weather": {
        "keywords": [
            "weather",
            "temperature",
            "climate",
            "forecast",
            "rain",
            "raining",
            "hot",
            "cold",
            "humid",
            "humidity",
            "wind",
            "windy"
        ]
    },

    "math": {
        "keywords": [
            "calculate",
            "solve",
            "simplify",
            "differentiate",
            "derivative",
            "integrate",
            "integral",
            "factorize",
            "factor",
            "expand",
            "limit",
            "square root",
            "sqrt"
        ]
    },

    "time": {
        "keywords": [
            "time",
            "clock",
            "current time"
        ]
    },

    "definition": {
        "keywords": [
            "define",
            "definition",
            "meaning",
            "what does",
            "what do you mean"
        ]
    },

    "wikipedia": {
        "keywords": [
            "what is",
            "what are",
            "who is",
            "who was",
            "where is",
            "where was",
            "when was",
            "when is",
            "why is",
            "how does",
            "tell me about",
            "explain",
            "describe"
        ]
    }
}

#fetching name for the user data
def get_name(text):
    phrases= [
        "my name is",
        "i am", "i'm"
    ]
    for phrase in phrases:
        if text.startswith(phrase + " "):
            name = text[len(phrase):].strip()
            if name:
                return name
    return None

#fetching user age for data
def get_age(text):
    words = text.split()
    if text.startswith("my age is "):
        age = text[len("my age is "):].strip()
        age = age.replace(" years old", "")
        age = age.replace(" years", "")
        age = age.replace(" year old", "")
        age = age.replace(" year", "")
        if age.isdigit():
            return int(age)
    if text.startswith("i am "):
        age = text[len("i am "):].strip()
        age = age.replace(" years old", "")
        age = age.replace(" years", "")
        age = age.replace(" year old", "")
        age = age.replace(" year", "")
        if age.isdigit():
            return int(age)
    return None

#fetching address
def get_address(text):
    if text.startswith("my address is"):
        return text[len("my address is"):].strip()
    if text.startswith("i live in"):
            return text[len("i live in"):].strip()
    return None

#data collecting center
def memory_response(text):
    if "what is my name" in text or "what's my name" in text:
        if memory["name"] is not None:
            return "your name is " + memory["name"] + "."
        return "I don't know your name yet."
    if "who am i" in text:
        if memory["name"] is not None:
            return "You are " + memory["name"] + "."
        return "I don't know your name yet."
    if "how old am i" in text:
        if memory["age"] is not None:
            return "You are " + str(memory["age"]) + " years old."
        return "I don't know your age yet."
    if "what is my age" in text:
        if memory["age"] is not None:
            return "You are " + str(memory["age"]) + " years old."
        return "I don't know your age yet."
    if "what is my address" in text:
        if memory["address"] is not None:
            return "Your address is " + memory["address"] + "."
        return "I don't know your address yet."
    if "where do i live" in text:
        if memory["address"] is not None:
            return "Your address is " + memory["address"] + "."
        return "I don't know your address yet."
    return None

#removing punctuations and unwanted spaces
def normalisation(text):
    text = text.strip().lower() #remove space #lowerspace
    if text.startswith("you:"):
        text = text[4:].strip()
    for ch in ["?","!",",","'"]:
        text=text.replace(ch,"") #replacing the character with an empty character literal
    text = ' '.join(text.split()) #splitting large space and resulting in one string with just one space between characters
    return text

#adding fuzzy matching technique.
#Fuzzy matching, or approximate string matching, 
# is a computer technique that finds text strings, words, 
# or data records that are similar rather than exact matches. 
# It assigns a similarity score to handle typos, spelling errors, 
# abbreviations, and formatting differences.
def fuzzy_match(text,choices,cutoff=0.7):
    match = difflib.get_close_matches(
        text, choices, n=1, cutoff = cutoff
    )
    if match:
        return match[0]
    return None

def contains_keyword(text,keywords):
    words = text.split()
    for keyword in keywords:
        keyword_words = keyword.split()
        if len(keyword_words) ==1:
            if keyword in words:
                return True
        else:
            if keyword in text:
                return True
    return False

#making an intention detector so that this cool bot can give answers based on users intention
def intent_detector(text):
    scores = {}
    for intent_name,data in intents.items():
        score = 0
        words = text.split()
        for keyword in data["keywords"]:
            if contains_keyword(text,[keyword]):
                score +=1
                continue
            if " " not in keyword:
                match = fuzzy_match(keyword, words, cutoff=0.8)
                if match is not None:
                    score += 1
        scores[intent_name] =score
    top_intent = max(scores,key=scores.get)
    if scores[top_intent]==0:
        return None
    
    #filter check
    #jarurat nhi thi aise hi dal diya :)
    # if ismques(text):
    #     return "math"
    # if isdques(text):
    #     return "definition"
    # if isweather(text):
    #         return "weather"
    # if istques(text):
    #     return "time"
    # if isfques(text):
    #         return "wikipedia"
    return top_intent

#segregating the words to be handled by apis. THE SO CALLED ENTITIES
def extract_entities(text,intent):
    entities = {}
    if intent == "weather":
        location = get_location(text)
        if location is not None:
            entities["location"] = location
    return entities
#checking question tags
def isfques(text):
    if not text:
        return False
    for phrase in pfp_phrase:
        if phrase in text:
            return False
    word_1 = text.split()[0]
    if word_1 in question_wrds:
        return True
    else:
        return False

#checking define quesiton tags
def isdques(text):
    for phrase in define_phrase:
        if text.startswith(phrase + " "):
            return True
    return False

#removing the question tags and leaving behind the keys to be searched up on wiki
def get_topics(text):
    for phrase in starting_phrases:
        prefix = phrase + " "
        if text.startswith(prefix):
            text = text[len(prefix):].strip()
            break
    return text
headers = {
    'User-Agent': 'PythonBot/1.0 (contact@example.com)'
}

#searching the word
def look_wiki(topic):
    try:
        response_wiki = requests.get(
            WIKI_SEARCH_URL,
            headers=headers,
            params = {
                "action":"query",
                "list":"search",
                "srsearch": topic,
                "srlimit":5,
                "format":"json"
            },
            timeout=10
        )
        response_wiki.raise_for_status()
        data = response_wiki.json()
        results = data.get("query",{}).get("search",[])
        titles=[result["title"] for result in results]
        return titles
    except requests.exceptions.RequestException as e:
        print("API Error:", e)
        return None

#chosing the top topic for the user
def top_wiki_title(topic, titles):
    if not titles:
        return None
    lower_titles = [t.lower() for t in titles]
    matches = difflib.get_close_matches(
        topic.lower(),
        lower_titles,
        n=1, #selecting the first topic for the wiki search/summary
        cutoff=0.5 #no results that are way too off --> feature of bot
    )
    if matches:
        matched_index = lower_titles.index(matches[0])
        return titles[matched_index]
    return None

#using the above method and getting summary
def get_sumry(title):
    concatenated_title = requests.utils.quote(title,safe="")
    url = ("https://en.wikipedia.org/api/rest_v1/page/summary/" + concatenated_title)
    try:
        response = requests.get(
            url,headers = headers, timeout=10
        )
        response.raise_for_status()
        data=response.json()
        return data.get("extract") #wikipedia response name (default)
    except requests.exceptions.RequestException:
        return None

#final call directly to the wikipedia
def get_wikipedia(topic):
    titles = look_wiki(topic)
    if titles is None:
        return None
    if not titles:
        return None
    title = top_wiki_title(
        topic,titles
    )
    if title is None:
        return None
    sumry = get_sumry(title)
    if sumry is None:
        return None
    if isAmbiguity(sumry):
        return None
    return title, sumry

#removing ambiguity of words
def isAmbiguity(sumry):
    if not sumry:
        return True
    if "may refer to:" in sumry.lower() and len(sumry)<200:
        return True
    return False

#removing the definition question tags and leaving behind the keys to be searceh up on wordnet
def get_word(text):
    for phrase in define_phrase:
        prefix = phrase + " "
        if text.startswith(prefix):
            return text[len(prefix):].strip()
    return None

#adding nltk library to get a more good response for definintions of words.
def get_definition(text):
    synsets = wrdnet.synsets(text)
    if not synsets:
        return None
    definition = synsets[0].definition()
    example_sentences = synsets[0].examples()
    # print(definition, example_sentences)
    return definition, example_sentences

#weather detecting 
def isweather(text):
    for tags in weather_tags:
        if tags in text:
            return True
    return False

#getting location data
def get_location(text):
    padded = " " + text + " "
    best_idx = -1
    best_marker_len = 0
    for marker in location_markers:
        idx = padded.find(marker)
        if idx != -1 and (best_idx == -1 or idx < best_idx):
            best_idx = idx
            best_marker_len = len(marker)
    if best_idx == -1:
        return None
    location = padded[best_idx + best_marker_len:].strip()
    for tag in weather_tags:
        location = location.replace(tag, "").strip()
    words = [w for w in location.split() if w not in trailing_noise]
    location = " ".join(words)
    return location if location else None

#getting weather details
def get_mausam(place):
    try:
        response = requests.get(
            WTTR_URL + "/" + requests.utils.quote(place),
            params={"format": "j1"},
            headers=headers, timeout=10
        )
        response.raise_for_status()
        data = response.json()
        current = data.get("current_condition", [None])[0]
        area = data.get("nearest_area", [None])[0]
        if current is None:
            return None, None
        resolved_name = None
        if area:
            area_name = area.get("areaName", [{}])[0].get("value")
            region = area.get("region", [{}])[0].get("value")
            resolved_name = area_name if area_name else region
        return current, resolved_name
    except requests.exceptions.RequestException as e:
        print("Weather API Error:", e)
        return None, None

#decoding the weather codes
def weather_decoder(code):
    weather_codes ={
        0: "Clear sky",
        1: "Mainly clear",
        2: "Partly cloudy",
        3: "Overcast",
        45: "Foggy",
        48: "Depositing rime fog",
        51: "Light drizzle",
        53: "Moderate drizzle",
        55: "Dense drizzle",
        61: "Slight rain",
        63: "Moderate rain",
        65: "Heavy rain",
        71: "Slight snowfall",
        73: "Moderate snowfall",
        75: "Heavy snowfall",
        80: "Slight rain showers",
        81: "Moderate rain showers",
        82: "Violent rain showers",
        95: "Thunderstorm",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail"
    }
    return weather_codes.get(code,"Weather condition unavailable")

#giving back all weather data 
    
#api response collector
def weather_response(place):
    result, resolved_name = get_mausam(place)
    if result is None:
        return None
    temperature = result.get("temp_C")
    humidity = result.get("humidity")
    wind = result.get("windspeedKmph")
    condition = result.get("weatherDesc", [{}])[0].get("value", "Weather condition unavailable")
    display_name = (resolved_name or place).title()
    return(
        "Weather in " + display_name + ":\n"
        "Temperature: " + str(temperature) + "°C\n"
        "Condition: " + condition + "\n"
        "Humidity: " + str(humidity) + "%\n"
        "Wind speed: " + str(wind) + " km/h"
    )
    
#is time ques chekcer
def istques(text):
    for phrase in time_tags:
        if phrase in text:
            return True
    return False
def get_time():
    current_time= datetime.now()
    return current_time.strftime("%I:%M:%S %p")

#maths tags and operators
def ismques(text):
    math_tags = {
        "calculate",
        "solve",
        "simplify",
        "differentiate",
        "derivative",
        "integrate",
        "integral",
        "factorize",
        "factor",
        "expand",
        "limit",
        "sqrt",
        "square root"
    }
    if any(operator in text for operator in ["-","+","/","*","^","=","√"]):
        return True
    for tag in math_tags:
        if tag in text:
            return True
    return False
def correct_phrase_if_incorrect(text):
    math_phrases = [
        "calculate",
        "solve",
        "simplify",
        "differentiate",
        "derivative",
        "integrate",    
        "integral",
        "factorize",
        "factor",
        "expand",
        "limit",
        "sqrt",
        "square root"
    ]
    words = text.split()
    if not words:
        return text
    first_word = words[0]
    if first_word in math_phrases:
        return text
    match = fuzzy_match(first_word, math_phrases, cutoff=0.7)
    if match is not None:
        words[0] = match
        return " ".join(words)
    return text

def convert_math_Exp(text):
    mat_phrases={
        "please calculate",
        "please answer",
        "calculate",
        "solve",
        "simplify",
        "differentiate",
        "derivative of",
        "derivative",
        "integrate",
        "integral of",
        "integral",
        "factorize",
        "factor",
        "expand",
        "limit",
        "sqrt",
        "square root",
        "solve the",
        "find the",
        "what is",
        "value of"
    }
    expression = text
    for tag in mat_phrases:
        if expression.startswith(tag+" "):
            expression = expression[len(tag):].strip()
            break
    return expression

def solver(text):
    try:
        text=correct_phrase_if_incorrect(text)
        #trying to make differentiation bot
        if text.startswith("differentiate "):
            expression = text[len("differentiate "):].strip()
            x = sympy.Symbol("x")
            expression = expression.replace("^","**")
            result = sympy.diff(sympy.sympify(expression),x)
            return "Derivative: "+str(result)
        if text.startswith("derivative of "):
            expression = text[len("derivative of "):].strip()
            x = sympy.Symbol("x")
            expression = expression.replace("^", "**")
            result = sympy.diff(sympy.sympify(expression),x)
            return "Derivative: " + str(result)
        
        #test for integration
        if text.startswith("integrate "):
            expression = text[len("integrate "):].strip()
            x = sympy.Symbol("x")
            expression = expression.replace("^","**")
            result = sympy.integrate(sympy.sympify(expression),x)
            return "Integral: " + str(result) + " + C"
        if text.startswith("integral of"):
            expression = text[len("integral of "):].strip()
            x = sympy.Symbol("x")
            expression = expression.replace("^","**")
            result = sympy.integrate(sympy.sympify(expression),x)
            return "Integral: " + str(result) + " + C"
        
        #testing limit exp
        if text.startswith("limit "):
            expression = text[len("limit "):].strip()
            #limit x^3 as x approches 3
            #limit x^3 (x->3)
            if " as x approaches " in expression:
                parts = expression.split(" as x approaches ")
                equation = parts[0].strip()
                value = parts[1].strip()
                x = sympy.Symbol("x")
                equation = equation.replace("^","**")
                result = sympy.limit(sympy.sympify(equation), x, sympy.sympify(value))
                return "Limit: " +str(result)
            return "Please use: limit expression as x approaches value"
        #factors
        if text.startswith("factorize"):
            expression = text[len("factorize "):].strip()
            expression = expression.replace("^","**")
            result = sympy.factor(sympy.sympify(expression))
            return "Factorized: " + str(result)
        
        #equations
        if "=" in text:
            parts =text.split("=")
            if len(parts) == 2:
                left = parts[0].strip()
                right = parts[1].strip()
                x= sympy.Symbol("x")
                left = left.replace("^","**")
                right = right.replace("^","**")
                equation = sympy.Eq(sympy.sympify(left) , sympy.sympify(right))
                result = sympy.solve(equation,x)
                if result:
                    return "x = "+str(result)
                return "No solution found."
        
        #simplify questions
        if text.startswith("simplify "):
            expression = text[len("simplify "):].strip()
            expression = expression.replace("^","**")
            result = sympy.simplify(sympy.sympify(expression))
            return "Simplified: " + str(result)
        
        #expand the following questions
        if text.startswith("expand "):
            expression = text[len("expand "):].strip()
            expression = expression.replace("^","**")
            result=sympy.expand(sympy.sympify(expression))
            return "Expanded: " + str(result)
        
        #easy peasy calc
        expression = convert_math_Exp(text)
        expression = expression.replace("^","**")
        expression = expression.replace("√","sqrt")
        result = sympy.simplify(expression)
        result = sympy.simplify(result)
        return "Answer: " + str(result)
    
    except Exception as e:
        print("Math Error name - ", e)
        return None
def fllwup(text):
    fllwup_phrases={
        "what about", "how about","and tomorrow",
        "and today", "what about tomorrow",
        "what about today", "how about tomorrow","how about today",
        "there", "that place", "the same place"
    }
    for phrase in fllwup_phrases:
        if phrase in text:
            return True
    return False

#IMPORTANT CONTEXT STORAGE TO GET A CONTINUOUS FLOW
context={
    "last_intent" : None,
    "last_location" : None,
    "last_topic" : None,
}

awaiting_location = False

#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN # 
#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN #
#MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN MAIN #

while True:
    user = input("You: ")
    user = normalisation(user)
    intent = intent_detector(user)
    entities = extract_entities(user,intent)
    if fllwup(user):
        if context["last_intent"] is not None:
            intent= context["last_intent"]
        if context["last_location"] is not None:
            entities["location"] = context["last_location"]
    print("Intent:", intent)
    print("Entities:", entities)
    
    #storage
    name = get_name(user)
    if name is not None:
        memory["name"]=name
        save_memory()
        print("Bot: Nice to meet you, "+name+"!")
        continue
    age = get_age(user)
    if age is not None:
        memory["age"]=age
        save_memory()
        print("Bot: I'll remember that you are " + str(age) + " years old.")
        continue
    address = get_address(user)
    if address is not None:
        memory["address"] = address
        save_memory()
        print("Bot: I'll remember that you live in " + address + ".")
        continue
    
    memory_result = memory_response(user)
    if memory_result is not None:
        print("Bot:", memory_result)
        continue
    
    #state word check
    if awaiting_location:
        place = user.strip()
        if not place:
            print("Bot: Please enter a location")
            continue
        context["last_location"]= place
        context["last_intent"]="weather"
        result = weather_response(place)
        if result is None:
            print("Bot: Sorry, I couldn't find weather data for '" + place + "'. Try a nearby bigger city or check the spelling?")
        else:
            print("Bot: ",result)
        awaiting_location =False
        continue
    
    #terminating words
    if user in terminators:
        print("Bot: Goodbye!")
        break
    
    
    #weather report
    if intent=="weather":
        place = entities.get("location")
        if place is not None:
            context["last_location"] = place
            
        if place is None:
            print("Bot: Which state would you like the weather for?")
            awaiting_location=True
            continue
        result=weather_response(place)
        if result is None:
            print("Bot: Sorry, I couldn't find weather data for '" + place + "'. Try a nearby bigger city or check the spelling?")
        else: 
            print("Bot: ", result)
        
        context["last_intent"]="weather"
        continue
    
    #time report
    if intent=="time":
        current_time = get_time()
        print("Bot: The current time is", current_time)
        continue
    
    #math caclulations
    if intent=="math":
        result = solver(user)
        if result is not None:
            print("Bot: ",result)
        else:
            print("Bot: I couldn't solve that mathematical expression.")
        continue
    
    #key_word looker
    found = False
    for keywords, reply in key_convo:
        #runs till each element in keywords
        if contains_keyword(user,keywords):
            print("Bot:",reply)
            found = True
            break
    if found:
        continue
    
    #definition check
    if intent=="definition":
        word = get_word(user)
        result = get_definition(word)
        if result is None:
            result1 = get_wikipedia(word)
            if result1 is None:
                print("I am still an undertrained chatbot. I don't know the above information. Please feel free to ask something else.")
            else:
                title, sumry = result1
                print("Bot: ",sumry)
                print("/source:",title)
            continue
        else:
            define, example = result #adds result values of get_definiton(returns define and example)
            print("Bot:", define) #prints word and its sentence
            if example:
                print("The word can be used as : ", example[0])
        continue
    
    #ques check
    if intent=="wikipedia":
        topic = get_topics(user)
        result = get_wikipedia(topic)
        if result is None:
            print("I am still an undertrained chatbot. I don't know the above information. Please feel free to ask something else.")
        else:
            title, sumry = result
            print("Bot: ",sumry)
            print("/source:",title)
        continue

    #if passes fails all the tests above then execute this at end;
    print("Bot: Sorry, I don't understand that yet.")